### ISSUE TITLE
`%` matching not working for do/end and def blocks

### ISSUE THREAD

**Issue by cweilemann** [vim-ruby/vim-ruby#357] opened 2017-09-07 20:41 UTC
I've tried everything I can think of to get `%` to match blocks for Ruby files, but nothing seems to work. `%` works for brackets, braces, etc. but not `def/end`, `do/end`, etc. blocks. 

Is there some way to test to verify I have the correct settings? Or are there known plugins that would overwrite this functionality?

**Comment by AndrewRadev** [comment] 2017-09-08 06:39
Are you sure you've installed the "matchit" plugin? It's a built-in plugin, but it has to be manually activated.  In short, you need to add this to your vimrc:

``` vim
packadd! matchit
```

If you don't have Vim 8 yet, it should be this instead:

``` vim
runtime macros/matchit.vim
```

Longer instructions can be found with [`:help matchit-install`](http://vimhelp.appspot.com/usr_05.txt.html#matchit%2dinstall).

**Comment by cweilemann** [comment] 2017-09-08 12:16
I do:

```
  3 set nocompatible      " We're running Vim, not Vi!
  4 syntax on             " Enable syntax highlighting
  5 filetype on           " Enable filetype detection
  6 filetype indent on    " Enable filetype-specific indenting
  7 filetype plugin on    " Enable filetype-specific plugins
  8 packadd! matchit
```

Note: I use the Janus plugin to get most other features, mostly because that's what I installed when I got started with Vim and I'm lazy and haven't done a "pick and choose" approach.

**Comment by cweilemann** [comment] 2017-09-08 12:18
And I'm not sure if any of this is useful:

```
[cweilemann@exponent ~ ]$ mvim --version                                                                                                                            !25205 [7:17:33]
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug 14 2017 13:58:37)
MacOS X (unix) version
Included patches: 1-891
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +find_in_path    -mouse_sysmouse  -tag_any_white
+arabic          +float           +mouse_urxvt     +tcl
+autocmd         +folding         +mouse_xterm     +termguicolors
+balloon_eval    -footer          +multi_byte      -terminal
+browse          +fork()          +multi_lang      +terminfo
++builtin_terms  +fullscreen      -mzscheme        +termresponse
+byte_offset     -gettext         +netbeans_intg   +textobjects
+channel         -hangul_input    +num64           +timers
+cindent         +iconv           +odbeditor       +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +transparency
+cmdline_compl   +jumplist        +perl            +user_commands
+cmdline_hist    +keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      +startuptime     -xpm
+eval            +mouse_dec       +statusline      -xsmp
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
+farsi           +mouse_netterm   +tag_binary      
+file_in_path    +mouse_sgr       +tag_old_static  
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -F/usr/local/opt/python/Frameworks -I/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib -F/usr/local/opt/python/Frameworks -L/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -framework CoreFoundation -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/usr/local/opt/python/Frameworks -framework Python  -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby    
```

**Comment by AndrewRadev** [comment] 2017-09-08 12:58
Alright, it does seem you're loading it. And the version is pretty recent, so shouldn't be an issue there.

Could you check the contents of `b:match_words`? Run this in your command-line, while editing a ruby file:

``` vim
echo b:match_words
```

**Comment by AndrewRadev** [comment] 2017-09-08 13:00
One other thing I just thought of -- could you try loading the matchit plugin with `packadd matchit`, instead of `packadd! matchit`? I highly doubt there would be a difference in this case, just want to be sure.

**Comment by cweilemann** [comment] 2017-09-08 13:05
Forgive the noob-ness... I think this is what you're looking for:

![screen shot 2017-09-08 at 8 04 00 am](https://user-images.githubusercontent.com/505478/30212868-52fa7648-946c-11e7-9c68-d310b1749c00.png)

`packadd matchit` appears to have worked... So perhaps problem solved?

**Comment by AndrewRadev** [comment] 2017-09-08 13:14
Ah, no, I meant without the `!` in the front. Vim also has a built-in `echo` command that outputs the value of the given expression -- in this case, a variable.

As for `packadd matchit` working, that's... interesting. From the documentation, it seems that the `!` at the end adds the package to the runtimepath, so it gets loaded at a later time. Vim-ruby *should* be loading its relevant files after it, since it's file-specific. Not sure why it doesn't work in this case, maybe matchit is being loaded lazily with the `packadd!`.

If it solves your problem, that's fine, I guess. I'll consider adding it to the documentation, though I'd like to experiment a bit, see why exactly this might happen. Something about the loading process, I guess.

I'm going to close the issue in this case, feel free to reopen it if the problem occurs again, or there's some other related complication.

**Closed by AndrewRadev** 2017-09-08 13:14 UTC

**Comment by cweilemann** [comment] 2017-09-08 13:24
Thanks @AndrewRadev - sorry if I wasted your time. I appreciate your help!

**Comment by AndrewRadev** [comment] 2017-09-08 13:49
No waste of time, no worries :). Glad the problem is fixed.
