### ISSUE TITLE
Change indent-style of trailing begin/case/if

### ISSUE THREAD

**Issue by kballenegger** [vim-ruby/vim-ruby#249] opened 2015-02-20 02:05 UTC
`ruby.vim` seems very opinionated about the proper indentation of trailing `begin`, `case`, `if`, etc. statements. It enforces this style:

``` ruby
def blah
  @blah ||= begin
              blah(:blah)
              blaher
            end
end
```

More often than not, I prefer this style:

``` ruby
def blah
  @blah ||= begin
    blah(:blah)
    blaher
  end
end
```

I keep a pretty strict 80-char line length limit, and this convention often makes it quite hard to properly style code. My alternative right now is to do this, but it's unnecessarily ugly:

``` ruby
def blah
  @blah ||= \
    begin
      blah(:blah)
      blaher
    end
end
```

**Comment by tpope** [comment] 2015-02-20 02:06
The last style (which is the one I generally favor) does not require that ugly backslash, FYI.

**Comment by kballenegger** [comment] 2015-02-20 02:22
Yeah. I always use backslash in line continuations as a habit, because sometimes it'll break when pasted into consoles, e.g.:

```ruby
# paste into pry, see breakage
blah.blah
  .blah
# this works
blah.blah \
  .blah
```

**Comment by kballenegger** [comment] 2015-02-20 02:23
Oh, I forgot to include this in the original issue: I'm not proposing that the default be changed. Just to provide an option to do it à-la `let g:ruby_begin_continuation_style = "blah"`

**Comment by kballenegger** [comment] 2015-02-20 02:29
There seems to be a bug with that last style btw, actually. Here's a similar example where the automatic indentation is off:

```ruby
  def self.new(service_name)
    (@superclass_cache ||= {})[service_name.to_sym] ||= \
      Class.new(InternalServiceController) do
      singleton_class.class_eval { alias :new :old_new }
    end.tap {|k| k.const_set(:SERVICE_NAME, service_name) }
  end
``` 

Here's what I'd expect:

```ruby
  def self.new(service_name)
    (@superclass_cache ||= {})[service_name.to_sym] ||= \
      Class.new(InternalServiceController) do
        singleton_class.class_eval { alias :new :old_new }
      end.tap {|k| k.const_set(:SERVICE_NAME, service_name) }
  end
```

**Comment by AndrewRadev** [comment] 2015-02-22 12:38
Let's start with the backslash.

You say that you always use backslash in line continuations just in case, but that seems like throwing out a lot of baby with very little bathwater. This works just fine pasted in irb:

``` ruby
@blah ||=
  begin
    blah(:blah)
    blaher
  end
```

In fact, anything that ends in an operator, `||=`, `+`, `,`, `.`, should work just fine pasted in irb, since the console can tell that the line is incomplete. The example you give with method calls is about the only thing I can think of that doesn't work:

``` ruby
blah.blah
  .blah
```

And it's perfectly natural that it doesn't work, since the very first line is perfectly complete. The console couldn't possibly tell that there's more to it by just looking at that one line. Which is why I prefer putting the dot on the end of the line to show that there's more to the expression coming up.

Now, if you insist on putting the dot on the next line, fine, it's a style thing. But then I'd really recommend that you make a habit of putting the backslash only in those cases, and not in line continuations in general.

The backslash is something we're probably never going to "support", partly because I'm not even sure what it would mean to "support" it. You give this example:

``` ruby
def self.new(service_name)
  (@superclass_cache ||= {})[service_name.to_sym] ||= \
    Class.new(InternalServiceController) do
    singleton_class.class_eval { alias :new :old_new }
  end.tap {|k| k.const_set(:SERVICE_NAME, service_name) }
end
```

I would argue that this is just fine. The backslash literally escapes the newline of that line, it works on a really, really low level. For instance, if you put a backslash in the middle of a string, you'll just get the `\\n` replaced with nothing by the interpreter. So, breaking up a string with a backslash is probably not what you want to do:

``` ruby
puts "foo \
  bar"
# => "foo   bar"
```

That's two spaces of indentation before "bar" and one after "foo".

So, arguably, the backslash means we just take the "real" line and use its indentation. Putting additional logic into the backslash seems counter to its real function.

This is all a bit philosophical, so for a purely practical reason -- it would probably be pretty hard, and I don't think backslash continuations are popular enough to warrant the effort (and risk of breakage and weird edge cases).

Now, if my backslash monologue has somehow convinced you that the multiline, Tim Pope-favored style is something you'd be up for using, that would be great. I started using that myself at some point and haven't looked back.

Otherwise, I'll look into it in the upcoming days. I've made this change before, but we had to revert it due to regressions, and in the end we decided it's not popular enough to be needed. At this point, though, I'd give it another shot.

**Comment by kballenegger** [comment] 2015-02-24 20:13
Your point about the backslash when it's unnecessary is fair. It's definitely a style thing. I can switch to using it only when necessary, for chained method calls with a leading period. (I find the leading period important for readability.) That said, the indentation issue here happens even without the backslash in the example I posted. 

Without a backslash, this is the indentation enforced by `vim-ruby`:

```ruby
    (@superclass_cache ||= {})[service_name.to_sym] ||=
      Class.new(InternalServiceController) do
      singleton_class.class_eval { alias :new :old_new }
    end.tap {|k| k.const_set(:SERVICE_NAME, service_name) }
```

I would expect:

```ruby
    (@superclass_cache ||= {})[service_name.to_sym] ||=
      Class.new(InternalServiceController) do
        singleton_class.class_eval { alias :new :old_new }
      end.tap {|k| k.const_set(:SERVICE_NAME, service_name) }
```

The issue here is that when a continuation opens an indent level, it doesn't take into account the +2 space indentation of the opening line. I would expect the lines that have the `do` and `end` statements to be at the same indent level, and the block's content to be at one indent level deeper.

**Comment by AndrewRadev** [comment] 2015-02-24 20:23
Ah, good point. I hadn't realized this is an issue as well. I'll look into it.

**Comment by AndrewRadev** [comment] 2015-02-28 16:36
I've created a separate issue for the do-block problem. I'll work on the the "continuation style" option soonish.

**Comment by lamont-granquist** [comment] 2016-01-14 17:12
So, I've used this for at least 5+ years or so and would still like to modify the behavior since I've never liked it.  I just recently discovered that rubocop supports the alternative style of end alignment:

```ruby
# Align if/end with the variable, not align with the if keyword
Lint/EndAlignment:
  AlignWith: variable
``

And I'd like to be able to convince vim to do the same so that I can get:

```ruby
whatever = if cond?
  stuff
end
```

Rather than either:

```ruby
whatever = if cond?
             stuff
           end
```

or:

```ruby
whatever =
  if cond?
    stuff
  end
```

The discussion about the backwhack line continuation seems to be a large distraction here and this is still an issue.

**Comment by chrisnicola** [comment] 2016-05-07 00:32
Curious if any more thought has been given to this issue. I too find the style of always aligning the block with the `if` statement rather than the assignment awkward.

**Comment by justjake** [comment] 2017-03-03 20:04
Bump. Does anyone have a solution to this issue?

**Comment by AndrewRadev** [comment] 2017-03-05 09:04
I'm sorry it took so long, but I think there's finally a solution to the continuation problem for assignments. To be honest, it wasn't really my work, it's all thanks to #329.

The documentation for the relevant options is here: https://github.com/vim-ruby/vim-ruby/blob/84afb552189060d1dae2d3154ba88454ee14fcda/doc/vim-ruby.txt#L143-L164

The short version is: putting this in your vimrc will align the block to the variable, and not to the statement:

``` vim
let g:ruby_indent_assignment_style = 'variable'
```

With this, I'll go ahead and close this issue, but if there are bugs with it or something, feel free to open a new issue to continue discussing it.

**Closed by AndrewRadev** 2017-03-05 09:04 UTC
Labels: indent
