### ISSUE TITLE
Incorrect syntax highlighting for this Ruby/Rails class. 

### ISSUE THREAD

**Issue by bluz71** [vim-ruby/vim-ruby#346] opened 2017-06-07 04:30 UTC
Hello vim-ruby support,

Minor quirk highlighting this Rails class:

```
class Album < ApplicationRecord
  scope :search, ->(query) do
    find_by_sql([<<-SQL.squish, query, "%#{query}%"])
                   SELECT albums.*
                     FROM albums
                     WHERE title @@ ?
                 SQL
  end
end
```

Both `end` statements are not highlighted.
No issue once the square brackets in the `find_by_sql` are removed.

Syntax highlighting Ruby I assume is difficult, and this example is a bit devious. I am not fussed about this, but I thought I would report it and let you figure out whether it is worth the trouble or not to look into this.

Best regards.

**Comment by AndrewRadev** [comment] 2017-06-10 07:45
From what I can understand of the code, the problem is that the opening square bracket and "opening" heredoc string intersect. 

The way that heredocs are highlighted, is that, everything from `<<-SQL` to the closing `SQL` is marked as "heredoc". The reason the rest of the line, like the `"%#{query}%"` part is highlighted, is because the entire first line, starting the `<<-SQL`, is marked as a "heredoc delimiter", and that particular syntax group can include anything. Unfortunately, the closing `]`, is also within this group, so the opening `[` ends up being unclosed.

I appreciate you opening an issue for this -- I hadn't noticed it myself, and it's definitely a bug. Unfortunately, I have absolutely no idea what we could do about this :/. This particular part of highlighting is a hack, I'm not even sure if it's possible to implement this "cleanly" in vim's syntax highlighting language. 

I'm going to leave this issue open in case @dkearns or @tpope comes up with an idea, either for a hacky fix, or for some rewrite of the heredoc code that might avoid issues like this. If I'm given a direction, I could experiment a bit myself, but, as it is, I don't have the slightest idea about how to approach the problem.

**Comment by bluz71** [comment] 2017-06-10 10:25
Yes, I would put this in the extreme corner-case category. Very very few folks will ever encounter this.

Just had a look, it looks like Atom does not like this code snippet much either and is treating the *heredoc* in a similar way to what you describe.

I am fine if this one is closed as **too-nasty-to-fix**. We can hope one day for AST aware syntax highlighting (in the far future).

Thanks.

**Comment by tpope** [comment] 2017-06-11 20:22
I'm still a sucker for a challenge, I guess.

**Closed by tpope** 2017-06-11 20:22 UTC

**Comment by bluz71** [comment] 2017-06-12 02:04
An unexpected nice surprise, thanks Tim and *vim-ruby* team.
