### ISSUE TITLE
highlights "end" wrong if  "if" is preceded by a regex literal in method definition

### ISSUE THREAD

**Issue by dfedde** [vim-ruby/vim-ruby#254] opened 2015-04-13 15:34 UTC
I searched though the issues a bit but did not find anything on this so.
If I have a definition like this:
``` ruby
def get_regex
  /some regex/ if false
end
```
The "end" is colored as if it is closing the if
where as:
```ruby
def get_regex
  (/some regex/) if false
end
```
highlights correctly.

**Comment by AndrewRadev** [comment] 2015-04-21 16:23
The problem is a common problem with trying to detect whether an expression is a regex literal or numeric division. The characters that are allowed in front of a multiline if-clause are defined with a regex like this: `[{:,;([<>~\*/%&^|+=-]`.

The point of this regex is that, because an if-clause is just an expression, something like this is valid:

``` ruby
result = 3 + if rand > 0.5
  4
else
  5
end

puts result
```

The same goes if the `+` is replaced with `/`.

That said, it doesn't seem likely that somebody would do something like this. One option is that we look for a `/` that's preceded by whitespace or something. Or just remove the slash from there completely and hope nobody decides to divide stuff by the result of if-clauses :).

I'm not sure what to decide. @tpope, since you usually take care of syntax stuff, do you have thoughts on the matter? If not, I'll think of it for a while and come up with a decision. Naturally, @dfedde, if you have any ideas, let me know.

**Comment by tpope** [comment] 2015-04-21 17:03
It's not perfect but I think dropping the slash from that character class would be acceptable. Dividing by a conditional has got to be super rare.

**Comment by AndrewRadev** [comment] 2015-04-30 17:07
Done. Let's see how long before someone hits the issue :). @dfedde, with this, I'll close the issue. Please reopen if you see any related problems.

**Closed by AndrewRadev** 2015-04-30 17:07 UTC

**Comment by fuadsaud** [comment] 2016-04-03 18:09
I'm getting a similar problem on my env. Not sure if this is even a problem with vim-ruby, but with the following code:

```
if foo
  do_bar
  do_baz

  do_zaz if zaz?
end
```

when I press `%` with the cursor over `end`, it jumps to the line right above it, when it should be jumping to the first line instead.
